export const ALL_MOVIES_SUCCESS = "ALL_MOVIES_SUCCESS";
export const ALL_MOVIES_START = "ALL_MOVIES_START";
export const ALL_MOVIES_FAILURE = "ALL_MOVIES_FAILURE";
export const ALL_MOVIES_END = "ALL_MOVIES_END";

export const SINGLE_MOVIE_SUCCESS = "SINGLE_MOVIE_SUCCESS";
export const SINGLE_MOVIE_START = "SINGLE_MOVIE_START";
export const SINGLE_MOVIE_FAILURE = "SINGLE_MOVIE_FAILURE";
export const SINGLE_MOVIE_END = "SINGLE_MOVIE_END";

export const GET_CHARACTERS_SUCCESS = "GET_CHARACTERS_SUCCESS";
export const GET_CHARACTERS_START = "GET_CHARACTERS_START";
export const GET_CHARACTERS_FAILURE = "GET_CHARACTERS_FAILURE";
export const GET_CHARACTERS_END = "GET_CHARACTERS_END";
